WAVES = {
	{--1
		{time = 2, enemy = "roach", spawnpoint = 1},
		{time = 2, enemy = "roach", spawnpoint = 4},
		{time = 3, enemy = "goblin", spawnpoint = 3},
		{time = 3, enemy = "goblin", spawnpoint = 2},
	},
	{--2
		{time = 2, enemy = "roach", spawnpoint = 1},
		{time = 2, enemy = "roach", spawnpoint = 4},
		{time = 3, enemy = "goblin", spawnpoint = 3},
		{time = 3, enemy = "goblin", spawnpoint = 2},
		{time = 6, enemy = "charger", spawnpoint = 5},
		{time = 8, enemy = "goblin", spawnpoint = 3},
		{time = 8, enemy = "goblin", spawnpoint = 4},
	},
	{--3
		{time = 2, enemy = "roach", spawnpoint = 1},
		{time = 2, enemy = "roach", spawnpoint = 4},
		{time = 2, enemy = "roach", spawnpoint = 3},
		{time = 2, enemy = "roach", spawnpoint = 2},
		{time = 2, enemy = "roach", spawnpoint = 5},
		{time = 2, enemy = "roach", spawnpoint = 6},
		{time = 4, enemy = "charger", spawnpoint = 5},
		{time = 4, enemy = "goblin", spawnpoint = 3},
		{time = 4, enemy = "goblin", spawnpoint = 4},
	},
	{--4
		{time = 2, enemy = "goblin", spawnpoint = 2},
		{time = 2, enemy = "charger", spawnpoint = 5},
		{time = 2, enemy = "goblin", spawnpoint = 3},
		{time = 2, enemy = "charger", spawnpoint = 6},
		{time = 2, enemy = "roach", spawnpoint = 1},
		{time = 2, enemy = "roach", spawnpoint = 4},
		{time = 10, enemy = "goblin", spawnpoint = 1},
		{time = 10, enemy = "goblin", spawnpoint = 2},
		{time = 10, enemy = "goblin", spawnpoint = 5},
		{time = 14, enemy = "giant", spawnpoint = 6},
	},
	{--5
		{time = 2, enemy = "giant", spawnpoint = 1},
		{time = 2, enemy = "giant", spawnpoint = 4},
		{time = 2, enemy = "charger", spawnpoint = 3},
		{time = 2, enemy = "charger", spawnpoint = 2},
		{time = 10, enemy = "goblin", spawnpoint = 1},
		{time = 10, enemy = "goblin", spawnpoint = 2},
		{time = 10, enemy = "goblin", spawnpoint = 3},
		{time = 10, enemy = "goblin", spawnpoint = 4},
		{time = 16, enemy = "giant", spawnpoint = 6},
		{time = 16, enemy = "giant", spawnpoint = 5},
	},
}