ANIMATION_DEFS = {
	["player"] = {
		["idle-up"] = {
			frames = { 4 },
			interval = 0.2,
			texture = "player",
			looping = true,
		},
		["idle-down"] = {
			frames = { 1 },
			interval = 0.2,
			texture = "player",
			looping = true,
		},
		["idle-left"] = {
			frames = { 6 },
			interval = 0.2,
			texture = "player",
			looping = true,
		},
		["idle-right"] = {
			frames = { 8 },
			interval = 0.2,
			texture = "player",
			looping = true,
		},
		["walk-up"] = {
			frames = { 3, 4 },
			interval = 0.2,
			texture = "player",
			looping = true,
		},
		["walk-down"] = {
			frames = { 1, 2 },
			interval = 0.2,
			texture = "player",
			looping = true,
		},
		["walk-left"] = {
			frames = { 5, 6 },
			interval = 0.2,
			texture = "player",
			looping = true,
		},
		["walk-right"] = {
			frames = { 7, 8 },
			interval = 0.2,
			texture = "player",
			looping = true,
		},
		["knocked-back"] = {
			frames = { 1, 5, 3, 7 },
			interval = 0.2,
			texture = "player",
			looping = true,
		},
		["spin"] = {
			frames = { 1, 2, 3, 4, 5, 6, 7, 8 },
			interval = 0.03,
			texture = "spin",
			looping = true,
		},
	},
	["sword"] = {
		["sword-down"] = {
			frames = { 1, 2, 3, 4 },
			interval = 0.05,
			texture = "sword",
			looping = false,
		},
		["sword-up"] = {
			frames = { 5, 6, 7, 8 },
			interval = 0.05,
			texture = "sword",
			looping = false,
		},
		["sword-left"] = {
			frames = { 9, 10, 11, 12 },
			interval = 0.05,
			texture = "sword",
			looping = false,
		},
		["sword-right"] = {
			frames = { 13, 14, 15, 16 },
			interval = 0.05,
			texture = "sword",
			looping = false,
		},
	},
	["goblin"] = {
		["walk-up"] = {
			frames = { 3, 4 },
			interval = 0.2,
			texture = "goblin",
			looping = true,
		},
		["walk-down"] = {
			frames = { 1, 2 },
			interval = 0.2,
			texture = "goblin",
			looping = true,
		},
		["walk-left"] = {
			frames = { 5, 6 },
			interval = 0.2,
			texture = "goblin",
			looping = true,
		},
		["walk-right"] = {
			frames = { 7, 8 },
			interval = 0.2,
			texture = "goblin",
			looping = true,
		},
	},
	["roach"] = {
		["walk-up"] = {
			frames = { 1, 2 },
			interval = 0.5,
			texture = "roach",
			looping = true,
		},
		["walk-down"] = {
			frames = { 5, 6 },
			interval = 0.5,
			texture = "roach",
			looping = true,
		},
		["walk-left"] = {
			frames = { 7, 8 },
			interval = 0.5,
			texture = "roach",
			looping = true,
		},
		["walk-right"] = {
			frames = { 3, 4 },
			interval = 0.5,
			texture = "roach",
			looping = true,
		},
	},
	["charger"] = {
		["walk-up"] = {
			frames = { 5, 6 },
			interval = 0.5,
			texture = "charger",
			looping = true,
		},
		["walk-down"] = {
			frames = { 1, 2 },
			interval = 0.5,
			texture = "charger",
			looping = true,
		},
		["walk-left"] = {
			frames = { 3, 4 },
			interval = 0.5,
			texture = "charger",
			looping = true,
		},
		["walk-right"] = {
			frames = { 7, 8 },
			interval = 0.5,
			texture = "charger",
			looping = true,
		},
		["charge-up"] = {
			frames = { 13, 14 },
			interval = 0.2,
			texture = "charger",
			looping = true,
		},
		["charge-down"] = {
			frames = { 9, 10 },
			interval = 0.2,
			texture = "charger",
			looping = true,
		},
		["charge-left"] = {
			frames = { 11, 12 },
			interval = 0.2,
			texture = "charger",
			looping = true,
		},
		["charge-right"] = {
			frames = { 15, 16 },
			interval = 0.2,
			texture = "charger",
			looping = true,
		},
		["windup-up"] = {
			frames = { 21, 22 },
			interval = 0.2,
			texture = "charger",
			looping = true,
		},
		["windup-down"] = {
			frames = { 17, 18 },
			interval = 0.2,
			texture = "charger",
			looping = true,
		},
		["windup-left"] = {
			frames = { 19, 20 },
			interval = 0.2,
			texture = "charger",
			looping = true,
		},
		["windup-right"] = {
			frames = { 23, 24 },
			interval = 0.2,
			texture = "charger",
			looping = true,
		},
		["recover-up"] = {
			frames = { 5, 6, 7, 8 },
			interval = 0.5,
			texture = "charger-recover",
			looping = true,
		},
		["recover-down"] = {
			frames = { 1, 2, 3, 4 },
			interval = 0.5,
			texture = "charger-recover",
			looping = true,
		},
		["recover-left"] = {
			frames = { 13, 14, 15, 16 },
			interval = 0.5,
			texture = "charger-recover",
			looping = true,
		},
		["recover-right"] = {
			frames = { 9, 10, 11, 12  },
			interval = 0.5,
			texture = "charger-recover",
			looping = true,
		},
	},
	["giant"] = {
		["walk-up"] = {
			frames = { 7, 8 },
			interval = 0.8,
			texture = "giant",
			looping = true,
		},
		["walk-down"] = {
			frames = { 1, 2 },
			interval = 0.8,
			texture = "giant",
			looping = true,
		},
		["walk-left"] = {
			frames = { 4, 5 },
			interval = 0.8,
			texture = "giant",
			looping = true,
		},
		["walk-right"] = {
			frames = { 10, 11 },
			interval = 0.8,
			texture = "giant",
			looping = true,
		},
		["windup-up"] = {
			frames = { 9 },
			interval = 0.5,
			texture = "giant",
			looping = true,
		},
		["windup-down"] = {
			frames = { 3 },
			interval = 0.5,
			texture = "giant",
			looping = true,
		},
		["windup-left"] = {
			frames = { 6 },
			interval = 0.5,
			texture = "giant",
			looping = true,
		},
		["windup-right"] = {
			frames = { 12 },
			interval = 0.5,
			texture = "giant",
			looping = true,
		},
		["attack"] = {
			frames = { 1, 2, 3, 4, 5, 6, 7, 8 },
			interval = 0.1,
			texture = "giant-spin",
			looping = true,
		},
	},
}
